global:
  scrape_interval: 15s
  evaluation_interval: 15s
rule_files:
  - /etc/prometheus/alerts.yaml
scrape_configs:
  - job_name: qwen
    static_configs:
      - targets: ['qwen:8080']

  - job_name: gemma
    static_configs:
      - targets: ['gemma:8080']

  - job_name: gpu
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ['gpu-exporter:9835']

  - job_name: dsh-otel
    static_configs:
      - targets: ['otel:8889']
