"""Image generation for agents: MCP tool generate_image and OpenAI-compatible /v1/images/generations.

Generation itself is tgbot/images.py (copied in at build time): the first running backend from
IMAGES_BACKENDS wins, or the one named by the request. Two instances run from this image: images
(sdxl, qwen-image) and images-uc (qwen-image-uc), which only Open WebUI can reach.
"""
import asyncio
import base64
import json
import logging
import os
import secrets
import time
from contextlib import asynccontextmanager
from pathlib import Path

from fastapi import Depends, FastAPI, HTTPException, Request, Response
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from mcp.server.fastmcp import FastMCP, Image
from mcp.server.transport_security import TransportSecuritySettings
from prometheus_client import CONTENT_TYPE_LATEST, CollectorRegistry, Counter, Histogram, generate_latest
from pydantic import BaseModel, Field

from images import Images
from llm import Unavailable

log = logging.getLogger("images")
PROMPT_LIMIT = 2000


class Settings:
    def __init__(self):
        self.api_key = os.getenv("IMAGES_API_KEY", "")
        if len(self.api_key) < 16:
            raise ValueError("IMAGES_API_KEY must be set (at least 16 characters)")
        self.backends = json.loads(os.getenv("IMAGES_BACKENDS", "{}"))
        if not self.backends:
            raise ValueError('IMAGES_BACKENDS must be a JSON object {"name": "http://host:port"}')
        self.workflows = json.loads(os.getenv("IMAGES_WORKFLOWS", "{}"))
        self.workflows_path = Path(os.getenv("IMAGES_WORKFLOWS_PATH", "/workflows"))
        self.timeout = float(os.getenv("IMAGES_TIMEOUT", "600"))
        self.name = os.getenv("IMAGES_NAME", "images")


class GenerationRequest(BaseModel):
    prompt: str = Field(min_length=1, max_length=PROMPT_LIMIT)
    model: str | None = None
    n: int = Field(1, ge=1, le=4)
    size: str | None = None  # accepted for compatibility; the generator workflow decides the size
    response_format: str = "b64_json"


class Generator:
    """Serialises generations: the GPU backends run one job at a time anyway."""

    def __init__(self, settings, images=None):
        self.settings = settings
        self.images = images or Images(settings.workflows_path, workflows=settings.workflows, prefix=settings.name)
        self.lock = asyncio.Lock()
        self.registry = CollectorRegistry()
        self.requests = Counter("images_requests_total", "Generations", ["source", "backend", "result"],
                                registry=self.registry)
        self.latency = Histogram("images_generation_seconds", "Generation duration incl. queueing", ["source"],
                                 buckets=(5, 15, 30, 60, 120, 300, 600), registry=self.registry)

    def backends(self, model=None):
        if model and model != "auto":
            if model not in self.settings.backends:
                raise Unavailable(f"Unknown model {model!r}; available: auto, {', '.join(self.settings.backends)}")
            return {model: self.settings.backends[model]}
        return self.settings.backends

    async def generate(self, prompt, model=None, source="api"):
        """(backend name, PNG bytes, seed)."""
        backends = self.backends(model)
        started = time.monotonic()
        try:
            async with self.lock:
                name, png, seed = await self.images.generate(backends, prompt, self.settings.timeout)
        except Unavailable:
            self.requests.labels(source, model or "auto", "unavailable").inc()
            raise
        self.requests.labels(source, name, "ok").inc()
        self.latency.labels(source).observe(time.monotonic() - started)
        return name, png, seed


def create_mcp(generator):
    mcp = FastMCP(
        generator.settings.name,
        instructions="Generates images with the local image models. Write prompts in English, "
                     "describing subject, style, composition and lighting.",
        stateless_http=True,
        # Reached by compose service name, so the default localhost-only Host check would reject it.
        transport_security=TransportSecuritySettings(enable_dns_rebinding_protection=False),
    )
    names = ", ".join(generator.settings.backends)

    @mcp.tool(description=f"Generate an image from a text prompt with a local model ({names}). "
                          "The image is shown to the user; do not repeat it as a link.")
    async def generate_image(prompt: str, model: str = "auto"):
        """prompt: detailed image description in English. model: auto or one of the available models."""
        name, png, seed = await generator.generate(prompt[:PROMPT_LIMIT], model, source="mcp")
        return [Image(data=png, format="png"), f"Image generated by {name}, seed {seed}."]

    return mcp


def create_app(settings=None, images=None):
    settings = settings or Settings()
    generator = Generator(settings, images)
    mcp = create_mcp(generator)
    mcp_app = mcp.streamable_http_app()
    bearer = HTTPBearer(auto_error=False)

    def authorized(credentials: HTTPAuthorizationCredentials | None = Depends(bearer)):
        if not credentials or not secrets.compare_digest(credentials.credentials, settings.api_key):
            raise HTTPException(401, "Invalid API key")

    @asynccontextmanager
    async def lifespan(app):
        async with mcp.session_manager.run():
            yield

    app = FastAPI(title=settings.name, lifespan=lifespan, docs_url=None, redoc_url=None)
    app.state.generator = generator

    @app.middleware("http")
    async def mcp_auth(request: Request, call_next):
        if request.url.path.startswith("/mcp"):
            header = request.headers.get("authorization", "")
            if not secrets.compare_digest(header.encode(), f"Bearer {settings.api_key}".encode()):
                return Response('{"detail":"Invalid API key"}', 401, media_type="application/json")
        return await call_next(request)

    @app.get("/health/live")
    async def live():
        return {"status": "ok"}

    @app.get("/health/ready")
    async def ready():
        return {"status": "ok"}

    @app.get("/metrics")
    async def metrics():
        return Response(generate_latest(generator.registry), media_type=CONTENT_TYPE_LATEST)

    @app.get("/v1/models", dependencies=[Depends(authorized)])
    async def models():
        return {"object": "list", "data": [{"id": name, "object": "model", "owned_by": "local"}
                                           for name in ("auto", *settings.backends)]}

    @app.post("/v1/images/generations", dependencies=[Depends(authorized)])
    async def generations(body: GenerationRequest):
        if body.response_format != "b64_json":
            raise HTTPException(400, "Only response_format=b64_json is supported")
        data = []
        try:
            for _ in range(body.n):
                _, png, _ = await generator.generate(body.prompt, body.model)
                data.append({"b64_json": base64.b64encode(png).decode(), "revised_prompt": body.prompt})
        except Unavailable as error:
            raise HTTPException(503, str(error)) from error
        return {"created": int(time.time()), "data": data}

    # Mounted last: the MCP app owns everything under /mcp.
    app.mount("/", mcp_app)
    return app
